name: PR Quality Check

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'refactor/**'

jobs:
  pr-check:
    name: Build, Test, Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install